Repository I-BIS-dev/hammers_corporate-site, pull requests merged in 2023-10, with the labels that each got.

#22 ヘッダー部分の画面開発
  assets/images/arrow-header.svg
  assets/images/phone-icon.svg
  assets/js/main.js
  assets/scss/common.scss
  assets/scss/foundation/_base.scss
  assets/scss/layout/_header.scss
  assets/scss/object/component/_button.scss
  assets/scss/object/component/_contact.scss
  assets/scss/object/component/_phoneicon.scss
  assets/scss/object/project/_inner.scss
  assets/scss/object/utility/_flex.scss
  assets/scss/object/utility/_font.scss
  css/common.css
  index.html
Labels: レビュー依頼

#23 footer部分の画面開発
  assets/images/arrow-topbtn.svg
  assets/scss/common.scss
  assets/scss/foundation/_base.scss
  assets/scss/layout/_footer.scss
  assets/scss/layout/_main.scss
  assets/scss/object/component/_button.scss
  css/common.css
  index.html
Labels: レビュー依頼

#25 問い合わせフォームのフォーム機能のみ開発
  contact/complete.php
  contact/confirm.php
  contact/index.php
Labels: レビュー依頼, 修正待ち

#24 topページの画面開発
  assets/images/3825.png
  assets/images/Ellipse 45.png
  assets/images/access-checkicon.svg
  assets/images/arrow-ctabtn.svg
  assets/images/arrow-ctasub.svg
  assets/images/asbestos1.jpg
  assets/images/asbestos1.png
  assets/images/asbestos2.jpg
  assets/images/asbestos2.png
  assets/images/feature1.png
  assets/images/feature2.png
  assets/images/feature3.png
  assets/images/flow1.png
  assets/images/flow2.png
  assets/images/flow3.png
  assets/images/flow4.png
  assets/images/mv-textbg.png
  assets/js/main.js
  assets/scss/common.scss
  assets/scss/foundation/_base.scss
  assets/scss/layout/_header.scss
  assets/scss/layout/_main.scss
  assets/scss/object/component/_button.scss
  assets/scss/object/component/_phoneicon.scss
  assets/scss/object/project/_headline.scss
  assets/scss/object/utility/_flex.scss
  assets/scss/object/utility/_font.scss
  css/common.css
  index.html
Labels: レビュー依頼

#28 会社概要ページの画面開発
  assets/images/3825.png
  assets/images/Ellipse 45.png
  assets/images/arrow-label.svg
  assets/images/office.jpeg
  assets/images/parking.jpeg
  assets/images/subvisual.jpg
  assets/scss/common.scss
  assets/scss/layout/_company.scss
  assets/scss/object/utility/_font.scss
  company/index.html
  css/common.css
Labels: レビュー依頼

#30 ベスターの強みページの画面開発
  assets/images/allin-img.png
  assets/images/research-1.png
  assets/images/research-2.png
  assets/images/shikaku.png
  assets/scss/common.scss
  assets/scss/layout/_merit.scss
  assets/scss/object/utility/_color.scss
  company/index.html
  css/common.css
  merit/index.html
Labels: レビュー依頼

#41 よくある質問ページの画面開発
  assets/js/main.js
  assets/scss/common.scss
  assets/scss/layout/_faq.scss
  assets/scss/layout/_main.scss
  assets/scss/object/utility/_font.scss
  assets/scss/object/utility/_padding.scss
  css/common.css
  faq/index.html
Labels: 中西さんのレビュー待ち

#42 フェードインアニメーション実装
  about/index.html
  assets/js/main.js
  assets/scss/common.scss
  assets/scss/object/animation/_fadein.scss
  company/index.html
  css/common.css
  faq/index.html
  index.html
  merit/index.html
  privacy/index.html
  privacy/sctl/index.html
Labels: 中西さんのレビュー待ち
